<link rel="icon" type="image/x-icon" href="../images/janata.ico">
<?php
include("../includes/db_connect.php");

// Show all errors (for development only — disable on production)
error_reporting(E_ALL);
ini_set('display_errors', 1);

// Check if bill_id is passed properly
if (!isset($_GET['bill_id']) || trim($_GET['bill_id']) === '') {
    die('Bill ID is missing.');
}

// Sanitize input
$billID = $conn->real_escape_string(trim($_GET['bill_id']));

// Fetch bill items
$query = "
    SELECT 
        b.billID, 
        b.billDate, 
        b.generated, 
        b.totalPaid,
        b.quantity, 
        b.price,
        m.name AS medicine_name
    FROM bill b
    LEFT JOIN medicine m ON b.medicine_fk = m.medicine_pk
    WHERE b.billID = '$billID'
";

$billResult = $conn->query($query);

if (!$billResult || $billResult->num_rows === 0) {
    die('Bill not found or no items.');
}

// Extract bill info
$billInfo = [
    'billID' => '',
    'billDate' => '',
    'generated' => '',
    'totalPaid' => 0
];
$items = [];

while ($row = $billResult->fetch_assoc()) {
    if (empty($billInfo['billID'])) {
        $billInfo['billID'] = $row['billID'];
        $billInfo['billDate'] = $row['billDate'];
        $billInfo['generated'] = $row['generated'];
        $billInfo['totalPaid'] = $row['totalPaid'];
    }

    $items[] = [
        'medicine_name' => $row['medicine_name'] ?? 'N/A',
        'quantity' => (int)$row['quantity'],
        'price' => (float)$row['price'],
        'subtotal' => (float)$row['price'] * (int)$row['quantity']
    ];
}
?>

<link rel="stylesheet" href="../css/style.css">

<!-- Shop Name -->
<div style="text-align: center; margin-bottom: 20px;">
    <h1 style="margin: 0;">Janata Pharmacy</h1>
    <small>Thank you for trusting us!</small>
</div>

<hr style="margin-bottom: 20px;">

<h2>Invoice</h2>
<p><strong>Bill ID:</strong> <?= htmlspecialchars($billInfo['billID']) ?></p>
<p><strong>Date:</strong> <?= htmlspecialchars($billInfo['billDate']) ?></p>
<p><strong>Generated By:</strong> <?= htmlspecialchars($billInfo['generated']) ?></p>

<table border="1" cellpadding="5" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>Medicine</th>
            <th>Quantity</th>
            <th>Price Each</th>
            <th>Subtotal</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($items as $item): ?>
            <tr>
                <td><?= htmlspecialchars($item['medicine_name']) ?></td>
                <td><?= htmlspecialchars($item['quantity']) ?></td>
                <td><?= htmlspecialchars(number_format($item['price'], 2)) ?></td>
                <td><?= htmlspecialchars(number_format($item['subtotal'], 2)) ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<h3 style="text-align: right; margin-top: 20px;">Total Paid: <?= htmlspecialchars(number_format($billInfo['totalPaid'], 2)) ?>৳</h3>

<!-- Print Button -->
<div style="text-align: center; margin-top: 30px;">
<button onclick="printInvoice()" class="btn-submit">🖨️ Print Invoice</button>

</div>
<style>
    body {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        background: #008080;
        color: #ffffff;
        padding: 30px;
    }

    .invoice-header {
        text-align: center;
        margin-bottom: 30px;
    }

    .invoice-header h1 {
        margin: 0;
        font-size: 32px;
    }

    .invoice-header small {
        color: #666;
    }

    /* Center the logo */
    .invoice-footer {
        text-align: center;
        margin-top: 30px;
    }

    .invoice-footer img {
        width: 150px; /* Adjust logo size for screen */
        height: 150px; /* Adjust logo size for screen */
    }

    /* Hide the print button during print */
    .no-print {
        display: none;
    }

    @media print {
        .btn-submit {
            display: none; /* Hide the print button during print */
        }

        /* Hide all default browser headers/footers */
        @page {
            margin-top: 0px;
            margin-bottom: 0px;
        }

        body {
            margin-top: 20px;
        }

        /* Hide the top and bottom margins */
        .header, .footer {
            display: none;
        }

        /* Remove default links */
        .no-print {
            display: none;
        }

        /* Resize the logo only during print */
        .invoice-footer img {
            width: 100px;  /* Adjust logo size for print */
            height: 100px; /* Adjust logo size for print */
        }

        /* Hide the print button during print */
        .no-print {
            display: none;
        }
    }
</style>

<script>
function printInvoice() {
    // Dynamically set the document title to Bill ID
    var originalTitle = document.title;
    
    // Pass PHP value to JavaScript by embedding it inside the script
    var billID = "<?= htmlspecialchars($billInfo['billID']) ?>"; // Get Bill ID from PHP to JS

    document.title = "Invoice-" + billID; // Temporary change title to BillID

    window.print(); // Trigger print

    // After print, restore original title
    document.title = originalTitle;
}
</script>
<div class="invoice-footer">
    <img src="../images/logo.png" alt="Janata Pharmacy Logo">
</div>

<?php include("../includes/footer.php"); ?>
