<link rel="icon" type="image/x-icon" href="../images/janata.ico">
<?php
include("../includes/db_connect.php");
include("../includes/header.php");

// Fetch all available dates
$dateResult = $conn->query("SELECT DISTINCT DATE(billDate) as bill_date FROM bill ORDER BY bill_date DESC");
?>

<h2 style="text-align:center;">All Bills</h2>
<link rel="stylesheet" href="../css/style.css">

<!-- Search Bill ID -->
<input type="text" id="searchInput" placeholder="Search Bill ID..." value="BILL-" style="margin: 10px 0; padding: 5px; width: 300px;">
<button onclick="searchTable()" class="btn-back" style="margin-left: 10px;">Search</button>
<button onclick="history.back()" class="btn-back" style="margin-left: 10px;">⬅ Back</button>

<!-- Dropdown for Date -->
<div style="margin-top: 20px; background: #f0fafa; padding: 20px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
    <h3 style="color: teal;">📅 Per Day Revenue Report</h3>

    <label for="dateSelect"><b>Select Date:</b></label>
    <select id="dateSelect" onchange="showPerDayRevenue()" style="margin-left: 10px; padding: 5px;">
        <option value="">-- Select Date --</option>
        <?php while($date = $dateResult->fetch_assoc()): ?>
            <option value="<?= $date['bill_date'] ?>"><?= $date['bill_date'] ?></option>
        <?php endwhile; ?>
    </select>

    <div id="revenueResult" style="margin-top: 20px;">
        <!-- Per Day Revenue will show here -->
    </div>
</div>

<!-- Bill List Table -->
<table id="dataTable" border="1" cellpadding="5" cellspacing="0" style="margin-top: 30px; width: 100%;">
    <thead>
        <tr>
            <th>Bill ID</th>
            <th>Date</th>
            <th>Total Paid</th>
            <th>Generated By</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    <?php
    $result = $conn->query("SELECT DISTINCT billID, billDate, totalPaid, generated FROM bill ORDER BY bill_pk DESC");
    while($row = $result->fetch_assoc()): ?>
    <tr>
        <td><?= htmlspecialchars($row['billID']) ?></td>
        <td><?= htmlspecialchars($row['billDate']) ?></td>
        <td><?= htmlspecialchars($row['totalPaid']) ?> ৳</td>
        <td><?= htmlspecialchars($row['generated']) ?></td>
        <td>
            <a href="print.php?bill_id=<?= urlencode($row['billID']) ?>" target="_blank" class="btn-back">🖨 Print</a>
        </td>
    </tr>
    <?php endwhile; ?>
    </tbody>
</table>

<script>
// Bill search
function searchTable() {
    var input = document.getElementById("searchInput").value.toLowerCase().trim();
    var table = document.getElementById("dataTable");
    var tr = table.getElementsByTagName("tr");

    for (var i = 1; i < tr.length; i++) {
        var td = tr[i].getElementsByTagName("td")[0];
        if (td) {
            var billId = td.textContent.toLowerCase().trim();
            if (billId.includes(input)) {
                tr[i].style.display = "";
            } else {
                tr[i].style.display = "none";
            }
        }
    }
}

// Show per day revenue
function showPerDayRevenue() {
    var date = document.getElementById("dateSelect").value;
    var revenueDiv = document.getElementById("revenueResult");

    if (date === "") {
        revenueDiv.innerHTML = "";
        return;
    }

    var xhr = new XMLHttpRequest();
    xhr.open("GET", "fetch_revenue.php?date=" + date, true);
    xhr.onload = function() {
        if (xhr.status === 200) {
            revenueDiv.innerHTML = xhr.responseText;
        }
    };
    xhr.send();
}
</script>

<?php include("../includes/footer.php"); ?>
